### ISSUE TITLE
Laravel Modules recognize the views

### ISSUE THREAD

**Issue by Litiano** [Haehnchen/idea-php-laravel-plugin#115]
I'm using https://github.com/caffeinated/modules.
Is there any way to recognize the views?

**Comment by adelf** [comment]
Have you tried Settings > Languages / Frameworks > PHP > Laravel > Views / Template ?

**Comment by Litiano** [comment]
Hello @adelf 
I saw this setup.
But the view call on the controller looks like this: `return view("module_name::view")`

https://github.com/caffeinated/modules/wiki/Resources

**Comment by adelf** [comment]
You can set up namespaces there. module views folder / module_name namespace

**Comment by Litiano** [comment]
Legal, it works.
Thank you @adelf .
Just one more question, is there any key word to interpret all the modules?
Type: app / Modules / * / Resource / Views, where * would be the keyword to interpret all paths.

**Comment by adelf** [comment]
Currently - no. Maybe in future... there will be something for auto-discovering modules views and other resources paths(translations for example)

**Comment by Litiano** [comment]
Thank you @adelf .

I'll close this issue.
