### ISSUE TITLE
NoSuchFieldError: STACK_DIRECTIVE 

### ISSUE THREAD

**Issue by aurelienborst** [Haehnchen/idea-php-laravel-plugin#117]
All my views/layouts get this error : 

NoSuchFieldError Error while indexingwww\resources\views\admin\examples\custom_datatables.blade.php

To reindex this file IDEA has to be restarted: STACK_DIRECTIVE

Ps : I'm using Laravel 5.4

**Comment by Haehnchen** [comment]
PhpStorm eap release?

**Comment by aurelienborst** [comment]
2016 1.0 (build 145.258)

**Comment by Haehnchen** [comment]
...woah crazy old release. sry not supporting this one anymore.
