### ISSUE TITLE
Foud bug with route parsing in some wery unusual way

### ISSUE THREAD

**Issue by Briareos17** [Haehnchen/idea-php-laravel-plugin#119]
I am using Route group:

    Route::group(['prefix' => 'profile', 'as' => 'profile.'], function(){
        Route::resource('about', 'ProfileController', [
            'only'       => ['show', 'edit', 'update'],
        ]);
        
        Route::resource('mangopay-user', 'MangopayUserController', [
            'except' => ['destroy'],
        ]);
    });

Artisan shows routes as:
- profile/about/{about} : profile.about.update, profile.about.edit, profile.about.show
- profile/mangopay-user : profile.mangopay-user.index, profile.mangopay-user.create

But laravel plugin parses it as:
- profile/about/{about} : profile.profile.about.edit
- profile/mangopay-user : profile.profile.mangopay-user.edit

**Comment by adelf** [comment]
Thanks. Haven't noticed about this behaviour. Seems, when 'as' directive exists, 'prefix' don't participate in route naming. Will be fixed.

**Comment by Haehnchen** [comment]
will be included in PhpStorm 2017.1 build
