### ISSUE TITLE
Single line Blade slots showing warning

### ISSUE THREAD

**Issue by aaronhuisinga** [Haehnchen/idea-php-laravel-plugin#121]
With the update for Components and Slots in the Laravel 5.4 release, I've found an issue.
Laravel allows slots to be expressed in a shorthand manner, for example:
```
@slot('title')
  My Slot Title
@endslot
```
can be shortened to:
```
@slot('title', 'My Slot Title')
```

While this renders properly with Blade, PHPStorm shows a "Directive is not closed" warning.

**Comment by Haehnchen** [comment]
Not a plugin issue.  nevertheless also reported to JetBrains please vote: https://youtrack.jetbrains.com/issue/WI-35648

**Comment by aaronhuisinga** [comment]
Thanks for pointing that out. I voted for the issue over at JetBrains!
