### ISSUE TITLE
Laravel components and slot indentation

### ISSUE THREAD

**Issue by hassanazimi** [Haehnchen/idea-php-laravel-plugin#122]
This is not really an issue but it would be great if you could fix it.

When I use @component like any other blade layout things inside it wont be indented if I use code reformat option by pressing cmd+alt+L. Indentation will make it really nice if possible.

```blade
@component('textarea')
Slot text
@slot('name') 
name 
@endslot
@slot('value') 
{{ $value }} 
@endslot
@endcomponent
```

**Comment by Haehnchen** [comment]
happily fixed in PhpStorm 2017.1 ;)
