### ISSUE TITLE
"goto for view templates" not working

### ISSUE THREAD

**Issue by SBhojani** [Haehnchen/idea-php-laravel-plugin#13]
Navigation from controller to view is not working for me:
![image](https://cloud.githubusercontent.com/assets/1684388/4698534/a65bf6f2-5835-11e4-9323-235329489e9c.png)
Autocompletion for the same view in the same controller is working correctly:
![image](https://cloud.githubusercontent.com/assets/1684388/4698552/d4439ca0-5835-11e4-9df7-95d46ea841c4.png)
@Haehnchen Any pointers?

**Comment by Haehnchen** [comment]
closing, its fixed
