### ISSUE TITLE
Plugin not working on PHPStorm 2017.1.1 Build 171.4163.3, with Laravel 5.4 

### ISSUE THREAD

**Issue by nonsapiens** [Haehnchen/idea-php-laravel-plugin#132]
I have a vanilla (no changes made) installation of Laravel 5.4.  I've installed the plugin, enabled it with autocomplete, and I have the IDE Helper installed too.

I can see no difference with the plugin enabled, and without.  No autocomplete, nothing.

I'm sure it's probably me doing something wrong, but I thought I'd file an issue nonetheless in the hope it can be fixed!  Would *love* to start getting into Laravel!

**Comment by nonsapiens** [comment]
I've also completely uninstalled and re-installed my PHPStorm, and still no joy

**Comment by jonnywilliamson** [comment]
Hmmm.

Obviously everyone's machine is different, but I don't think that's right. 

I've just done the exact same thing, vanilla install of 5.4 and it's working just fine. Here's a short demo:

[![Fresh Laravel Installation](https://cloud.githubusercontent.com/assets/2513663/24837134/f9021772-1d24-11e7-83fd-73e9da217532.png)](https://vimeo.com/212455718 "Laravel plugin and fresh laravel install")

**Comment by nonsapiens** [comment]
Yeah, I tried everything.  This is on Ubuntu 16.04.2 LTS.
Not sure what to do.  Are there logs I can look at to see what it's doing -
maybe there's some feedback I can provide to isolate the issue ... would
*dearly* love to get this working

**Comment by nonsapiens** [comment]
Actually, hang on ...  Your video was very helpful, in that it helped me
understand that *some* of the features are working.  For instance,
everything you did in your video, I could do in mine.  Stuff that didn't
work (that I believe should work) are things like Route autocomplete, e.g:

[image: Inline images 1]

Or the understanding of Facades, e.g. working with DB::

[image: Inline images 2]

Or, as one of the demos show, working with Config::

[image: Inline images 3]

That's what I'm having issues with.  Your Views autocomplete, as per your
video, worked as expected :-)

**Comment by adelf** [comment]
Can't see your images. But seems you have to run 'php artisan
ide-helper:generate'

**Comment by nonsapiens** [comment]
Okay - I'm happy to admit that I am an idiot, and your suggestion worked :-D  Excuse me whilst I go whip myself for missing out that step.

You sir, are a legend.

**Comment by jonnywilliamson** [comment]
Close the issue?

**Comment by Haehnchen** [comment]
so closed
