### ISSUE TITLE
Autocompletion for query scopes

### ISSUE THREAD

**Issue by screenager** [Haehnchen/idea-php-laravel-plugin#139]
How complex is it support autocompletion of query scope methods of models?
```
class MyModel extends Model {
  function scopeActive($query) {
    return $query->whereActive(true);
  }
}
```

So when you start typing "MyModel::ac" there appears "MyModel::active()" ?

Just an idea..

**Comment by adelf** [comment]
Have you tried ide-helper:models command? It generates what you need.
https://github.com/barryvdh/laravel-ide-helper#automatic-phpdocs-for-models

**Comment by screenager** [comment]
Did not know of this command, thanks!

**Comment by lsalazarm99** [comment]
Laravel Ide Helper only helps when the scope is the very first method you use when you are building the query.

If you need to use 2 scopes or something like the following (assuming an "active" scope), it's not working.

```php
$models = YourModel::query()
    ->when(
        $request->boolean('isActive', false),
        function (Builder $query) {
            $query->active(); // Warning: Method 'active' not found in \Illuminate\Database\Eloquent\Builder
        }
    )
    ->get()
;
```

**Comment by daverogers** [comment]
In that case ...
### >= PHP 8
```php
$models = YourModel::query()
    ->when(
        $request->boolean('isActive', false),
        function ($query) {
            /** @var MyModel|Builder $query */
            $query->active();
        }
    )
    ->get()
;
```
### <= PHP 8
```php
$models = YourModel::query()
    ->when(
        $request->boolean('isActive', false),
        function (MyModel|Builder $query) {
            $query->active();
        }
    )
    ->get()
;
```

no?
