### ISSUE TITLE
Provide support for @includeWhen Blade directive

### ISSUE THREAD

**Issue by bazzik** [Haehnchen/idea-php-laravel-plugin#142]
Please provide support for `@includeWhen` Blade directive (Laravel 5.4.14+ or so).

The first parameter is a condition that if evaluated to true will include a view declared in the second parameter.

```
@if ($user->isAdmin)
  @include('admin.panel')
@endif
```
vs
```
@includeWhen($user->isAdmin, 'admin.panel')
```

**The support required:** completion assistance + Ctrl+Click navigation for views in 2nd parameter (similarly to how it's done for `@include` directive in 1st parameter).

**P.S.** I hope it's a right place to report this -- I assume that existing functionality for `@include` is offered by your plugin and not PhpStorm.

**Comment by Haehnchen** [comment]
done
