### ISSUE TITLE
Errors with Blade Sintax

### ISSUE THREAD

**Issue by ErSulba** [Haehnchen/idea-php-laravel-plugin#147]
lately this has been an issue when a i try to review my templates, there's this example from the default template of laravel:
![error phpstorm](https://user-images.githubusercontent.com/15116871/29534488-388bbb96-8684-11e7-9cf6-d987a526b803.PNG)

as you can see the 
the directive "if" is closed with it respective "endif" at the line 24

**Comment by bbashy** [comment]
I bet if you remove the `@auth` part, it won't show the error. Basically the new auth keyword is throwing it off.

**Comment by bazzik** [comment]
@ErSulba 
Seems like PhpStorm is unaware that `@else` can be used inside `@auth`...`@endauth` block.

Please report it to PhpStorm Issue Tracker ( https://youtrack.jetbrains.com/issues/WI ) as it's the one responsible for handling such logic and not this plugin.

**Comment by Haehnchen** [comment]
external issue
