### ISSUE TITLE
Provide support for @includeFirst Blade directive

### ISSUE THREAD

**Issue by bazzik** [Haehnchen/idea-php-laravel-plugin#152]
Replaces:
```
@if(view()->exists('custom-template'))
    @include('custom-template')
@else
    @include('default-template')
@endif
```
With:
```
@includeFirst(['custom-template', 'default-template'])
```
https://github.com/laravel/framework/pull/21172

**The support required:** completion assistance & Ctrl+Click navigation for views (similarly to how it's done for `@include` directive in 1st parameter).

**Comment by Haehnchen** [comment]
done
