### ISSUE TITLE
Facade autocomplete not working

### ISSUE THREAD

**Issue by jordyvandomselaar** [Haehnchen/idea-php-laravel-plugin#153]
As the title says, facades don't get autocompletions =(

![image](https://user-images.githubusercontent.com/12712484/31427809-e0ea00c0-ae68-11e7-82ae-6482bdee89dd.png)

**Comment by Haehnchen** [comment]
Missing: Laravel IDE Helper

> Note You must install and use the Laravel IDE Helper in order for PhpStorm to know how to find the Laravel classes.
