### ISSUE TITLE
idea-php-laravel-plugin Unable to work properly

### ISSUE THREAD

**Issue by DavidNineRoc** [Haehnchen/idea-php-laravel-plugin#186]
## Env
* PHPStorm 2018.1
* Laravel 5.5.40
****
1. Install plugin and active it per Project under "Settings > Languages & Frameworks > PHP > Laravel"
![image](https://user-images.githubusercontent.com/28035971/40226981-d5254912-5abf-11e8-96f4-a31f9f0c1329.png)

2. I have installed laravel-ide-helperand have generated the configuration file
![image](https://user-images.githubusercontent.com/28035971/40227020-ecd7d5de-5abf-11e8-83d7-ba4d503bf68e.png)
3. The view is not configured because I use the default path
![image](https://user-images.githubusercontent.com/28035971/40227070-0c213bba-5ac0-11e8-84af-6f7a39a530b2.png)
4. (Enable autopopup for completion in plugin setting)
![image](https://user-images.githubusercontent.com/28035971/40227336-ce4c2060-5ac0-11e8-97b9-fc45bc36d293.png)
****
* But I still can't use it properly.
![image](https://user-images.githubusercontent.com/28035971/40227371-ea087ce0-5ac0-11e8-91c6-3d07c027b64e.png)

**Comment by liujundezhanghao** [comment]
Like us, can you help me?
