### ISSUE TITLE
Implement Translation component support

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-laravel-plugin#19]
You could also add support for blade's `@lang()` (equivalent to `{{ trans() }}`) and `@choice()`  (equivalent to `{{ choice() }}`). 
I don't know if it is already done but at least in my L5 project it doesn't work.

**Comment by ozanhazer** [comment]
+1

**Comment by SkysoulDesign** [comment]
+1

**Comment by Milewski** [comment]
+1

**Comment by Haehnchen** [comment]
done
