### ISSUE TITLE
Phpstorm 2018.3.1 Laravel 5.5 new project plugin not working

### ISSUE THREAD

**Issue by icecoldPHP** [Haehnchen/idea-php-laravel-plugin#203]
# env

Debian 9

phpstorm 2018.3.1
Latest laravel plugin

# steps taken

* `composer create-project laravel/laravel testing "^5.5"`
* `composer require barryvdh/laravel-ide-helper`
* follow install steps for ide-helper
* `php artisan make:controller TestingController`
* add method to the controller
* `php artisan ide-helper:generate`
* open web.php Route::get('/', 'Testing.......')
* popup with No suggestions

**Comment by adelf** [comment]
Please check #201
ide helper haven't released a version with needed fix, you can try dev-master.

**Comment by icecoldPHP** [comment]
Differen

> Please check #201
> ide helper haven't released a version with needed fix, you can try dev-master.

Thnx it worked by using dev-master of ide-helper
