### ISSUE TITLE
Laravel 5.7 support for ?? operator

### ISSUE THREAD

**Issue by alvinbakker** [Haehnchen/idea-php-laravel-plugin#204]
When will the ?? operator be supported for Laravel 5.7 blades?

**Comment by andyvenus** [comment]
That's just a PHP feature, so as long as your project settings have the 'PHP language level' set to 7, you shouldn't have any issues.

**Comment by cedricziel** [comment]
Exactly as @andyvenus states. It's more of a platform issue.
