### ISSUE TITLE
is this project dead ?

### ISSUE THREAD

**Issue by Urjashee** [Haehnchen/idea-php-laravel-plugin#212]
Has this project been abandoned ?

**Comment by adelf** [comment]
I’m going to add some features... but don’t have time

**Comment by Urjashee** [comment]
With recent updates in phpstorm , this plugin doesn't work correctly .

**Comment by Urjashee** [comment]
Waiting eagerly for your updates

**Comment by cedricziel** [comment]
I wouldnt say it's dead. Everyone is welcome to participate :)

Added some new platform versions to the travis tests (#213)
