### ISSUE TITLE
Enable Finding Symbol with Class@Method format

### ISSUE THREAD

**Issue by diogogomeswww** [Haehnchen/idea-php-laravel-plugin#237]
Right now we can find an symbol with the Class::Method format.

But Laravel uses Class@Method everywhere.

So whenever I want to navigate to that method I need to copy the text and change the @ to :: to work.

It would be very helpful if it would work out-of-the-box with the Class@Method format.

Example of searching for Class@Method:
![image](https://user-images.githubusercontent.com/11543163/61855374-d9edcf80-aeb7-11e9-9297-b7a086c4b501.png)

But if I search for Class::Method
![image](https://user-images.githubusercontent.com/11543163/61855401-ea9e4580-aeb7-11e9-8b6a-fe770493b3d0.png)

Thanks for great plugin!

**Comment by Haehnchen** [comment]
do you have an example snippet where you expect it?

**Comment by diogogomeswww** [comment]
Hi @Haehnchen I've edited the description to include the screenshots of examples.
Please let me know what you think about it and if I can help.

**Comment by Haehnchen** [comment]
got it. this search its not anything by this plugin. i am wondering why you need to copy it. the right way would to click directly in the editor string.

A click behavoir should be added in the editor, this can be approved. so where do you copied to from? ;)

**Comment by diogogomeswww** [comment]
Ah, got it.
So the search can't be enhanced/changed by the plugin, correct?

If true we can close this issue, since the string Class@Method name won't appear in the editor.
It will appear on the terminal when we run: `php artisan route:list`, in the browser in `laravel telescope`, a few screenshots below:
![image](https://user-images.githubusercontent.com/11543163/61876991-00c2fa80-aee6-11e9-931b-5f21dcc103bb.png)

![image](https://user-images.githubusercontent.com/11543163/61877027-1a644200-aee6-11e9-9184-696ba2b21cf8.png)

**Comment by adelf** [comment]
I can only suggest use PhpStorm style of navigating. 
Navigate > Class.. or Ctrl-N or Cmd-N . Then enter, for example "SDC" for finding "SkusDisplayController" class and then Ctrl-12(Cmd-F12) and enter "index". Pretty quickly.

**Comment by diogogomeswww** [comment]
yes, I know, but it could be faster if it would work with Class@Method formatting.

But thanks for your help and attention!

**Comment by dorkyboi** [comment]
In case its still relevant for someone...

You can use PhpStorm's `Ctrl+Click` navigation if building routes like
`Route::post('logout', [LoginController::class, 'logout'])->name('logout');`
Works for both `LoginController` **_and `logout` method_**.

For that you just need to do three simple steps:
1. use Route facade (`use Illuminate\Support\Facades\Route;`)
2. use any controller class you need (or you may leave full qualified namespaces) 
3. change `$namespace` variable in `App/Providers/RouteServiceProvider` to empty string, so laravel would not append anything to already fully qualified controller namespaces

Of cource, used imports may stack up for big projects, but PhpStorm will conviniently collapse them, so you won't even notice.
