### ISSUE TITLE
Laravel 5 {!! raw !!} blade support

### ISSUE THREAD

**Issue by martinlindhe** [Haehnchen/idea-php-laravel-plugin#26]
Hello!

In Laravel 5, they added the syntax {!! code.. !!} in the blade template engine, this has the same meaning as tripple curlies {{{ code }}}, in laravel 4, but the advantage of being more visually obvious.

It dont seem to be recognized by this plugin, so intellisense on the code snippets in there doesn't work. 
Would be great if this could be supported!

Some info: https://laravel-news.com/2014/09/laravel-5-0-blade-changes/

**Comment by rscafi** [comment]
@martinlindhe this plugin isn't responsible for blade intellisense support. It's phpstorm's native.
Go to *Settings > Languages & Frameworks > PHP > Blade* and update tags.

**Comment by martinlindhe** [comment]
Oh, you're right. Thanks for pointing it out to me!
