### ISSUE TITLE
Blade conditionals seem to be acting up

### ISSUE THREAD

**Issue by michaelbrewster** [Haehnchen/idea-php-laravel-plugin#29]
Seems that blade tags that do match, don't get picked up and as a result they're marked as an error

http://d.pr/i/18au1

**Comment by g33kidd** [comment]
I just had this problem and found this closed issue. Not sure if it helps or not. https://github.com/Haehnchen/idea-php-laravel-plugin/issues/26

**Comment by Haehnchen** [comment]
Pls, report to PhpStorm. Blade engine is external
