### ISSUE TITLE
Navigation to view in custom view folder without namespace Problem

### ISSUE THREAD

**Issue by Samyyno1** [Haehnchen/idea-php-laravel-plugin#30]
When i have a view in a custom folder like `app/someFolder/views` and add that folder in the settings without a namespace and then use an `@include("app.somFolder.views.myview")` and then try to navigate to that view using `ctrl + click` then I get a `Not found` message. BUT if i change the include like so `@include("::app.somFolder.views.myview")` it works, but then processing of the template doesn't work. After looking into the sourcecode I found the problem: 
In the file `/src/de/espend/idea/laravel/view/ViewCollector.java` on line `83` there is a check wether the `namespace` entry is NULL. If i don't enter any namespace in the configuration then the namespace isn't NULL because it is represented as namespace="" in the `laravel-plugin.xml` resulting in not being null.
My current workaround is to edit the `laravel-plugin.xml` and remove the empty namespace attribute what "fixes" the problem.
Changing the source to check whether the namespace is empty or not instead of checking for just NULL would be cleaner since the user has no possebility whatsoever to set the namespace to NULL only using the settings.

**Comment by dnish** [comment]
Yeah, just having the same problem.

**Comment by FractalizeR** [comment]
Yep, same problem ;)

**Comment by Haehnchen** [comment]
fixed
