### ISSUE TITLE
Laravel 5 compatibility

### ISSUE THREAD

**Issue by jaroslawziolkowski** [Haehnchen/idea-php-laravel-plugin#32]
Do you plan upgrade for Laravel 5 (with blade) compatibility? For example autocomplete for blade {!! !!} tag.

**Comment by Haehnchen** [comment]
yes, i will work on it

**Comment by rscafi** [comment]
@jaroslawziolkowski this plugin isn't responsible for blade intellisense support. It's phpstorm's native.
Go to `Settings > Languages & Frameworks > PHP > Blade` and update tags to match L5 and you're done with it.

**Comment by jaroslawziolkowski** [comment]
@rscafi I have {!! as Blade tags. But autocomplete not work. Phpstor not mark {!! tag as error but autoclose only {{ }}

**Comment by rscafi** [comment]
Your config should be like this:
![2015-04-07-083301_1024x691_scrot](https://cloud.githubusercontent.com/assets/6104262/7022304/bb0ad406-dd00-11e4-892d-06931b9f4e43.png)

**Comment by jaroslawziolkowski** [comment]
@rscafi 
I have same config. And phpstorm works correct in general. But wien I set {{ IIDE auto close tag by }}
When I set {!! I can write code but I have to close !!} manually.

It's not big problem. but auto close is comfortable.

For you it works?

**Comment by rscafi** [comment]
Oh, now I see the issue. I have the same problem and it's a really annoying behavior, buggy imo.
But anyway, it's PhpStorm's responsability.

**Comment by terbooter** [comment]
I also missed quick navigation to definition in Laravel5
In Larave4 I can jump to definition by F4 key (or Ctrl+click)
```PHP
Route::get('/', 'HomeController@index');
```

**Comment by Bulmer** [comment]
Is there a fix for the new Blade {!! !!} autocomplete yet?

**Comment by s4m4n** [comment]
+1 for laravel 5 support

**Comment by Haehnchen** [comment]
`{!! !!}` is PhpStorm issue. Route and some other laravel5 added in `0.8`
