### ISSUE TITLE
View competition is not working with Phpstorm 9.0

### ISSUE THREAD

**Issue by Alekc** [Haehnchen/idea-php-laravel-plugin#36]
After upgrade to phpstorm 9 (from 8) return view() in controller is not offering template name suggestion anymore.

Maybe other features are broken as well. Can someone confirm this one?

**Comment by darthmaim** [comment]
This works for me.

**Comment by jonnywilliamson** [comment]
@darthmaim I'm not getting template name suggestion either. Any idea what might be different with your system to allow it to work?

I'm on windows 7 x64.

**Comment by darthmaim** [comment]
Hmm, OSX 10.10.3 here and it works.

<img width="609" alt="bildschirmfoto 2015-07-31 um 13 50 53" src="https://cloud.githubusercontent.com/assets/2511547/9006772/839f1a50-378b-11e5-8692-db3441d7b782.png">

**Comment by jonnywilliamson** [comment]
Mmmmm.

It was a straight forward update from phpstorm 8 - 9. 

![phpstorm](https://cloud.githubusercontent.com/assets/2513663/9021038/2dae6d6c-3826-11e5-8a92-85cb045fcf7c.png)

![phpstorm2](https://cloud.githubusercontent.com/assets/2513663/9021043/96633c70-3826-11e5-90eb-cdd4d3a3b95f.png)

**Comment by jonnywilliamson** [comment]
Wait, just found the answer @Alekc 

Looks like the upgrade unticked this box:

As per the docs
>Once installed, you must activate per-project by going to Settings > Laravel Plugin and clicking "Enable for this project".

![phpstorm3](https://cloud.githubusercontent.com/assets/2513663/9021049/f42d61aa-3826-11e5-90a0-427e057998f4.png)


Once I clicked enabled everything worked again.

Simple :)
