### ISSUE TITLE
Where is "Laravel IDE Helper Generator"?

### ISSUE THREAD

**Issue by malhal** [Haehnchen/idea-php-laravel-plugin#37]
Following the Install instructions and got stuck on step 2, can't find this anywhere in PHPStorm.

**Comment by malhal** [comment]
The problem is the plugin description isn't clear but the readme here on github has the link. I'd suggest adding the link to the description in the plugin inside PHPStorm to help others.

**Comment by rscafi** [comment]
Here it is.
https://github.com/barryvdh/laravel-ide-helper
