### ISSUE TITLE
Proposal: Laravel services autocomplete

### ISSUE THREAD

**Issue by vedmant** [Haehnchen/idea-php-laravel-plugin#42]
I use Symfony plugin for another project on Symfony, and It has great feature, it can check and autocomplete services instance methods got from services container: http://screencast.com/t/UaqvV2B6 . But there is no way to do the same with Laravel service container, so If I pull a request from container like this app('request')-> I will not be able to see request class methods as well as IDE can't check if parameters are correct, and so on... However It will be much harder to implement as services in Laravel instantiated dynamically, if even possible at all...

**Comment by jonnywilliamson** [comment]
Is this not what you are after?

https://github.com/barryvdh/laravel-ide-helper#phpstorm-meta-for-container-instances

**Comment by vedmant** [comment]
Wow, I use ide helper, but I didn't notice this feature, thank you, I'll check it!

**Comment by Haehnchen** [comment]
Should be easy to implement. Collect all cild classes of `ServiceProvider` and find `app` calls
```
\Illuminate\Support\ServiceProvider
$this->app->singleton
```

**Comment by Haehnchen** [comment]
some improvements still possible by should be fine for now

**Comment by EvgeniyN** [comment]
Hi all!
Your plugin is awesome, but this feature are really broken.

Here u implement autocomplete for app() function calls, but it's show really broken values.
If u try to extend Application class or replace default Router it still show old values end references. Register some facades with service providers - they don't displayed at all.
When u try to get list of available bindings (Alt+Space inside app('')) your plugin and simple .phpstorm.meta generated by ide-helper show completely different values.

So I try to ask U: Make this feature optional via settings or just remove it. It's really drives me crazy and whole our team to ))

Please. Please. Please.
