### ISSUE TITLE
Namespace for translations

### ISSUE THREAD

**Issue by sebastienheyd** [Haehnchen/idea-php-laravel-plugin#57]
When using a module package, ctrl+click does not work on translations.

Like views / template, translations can use namespace (see : https://github.com/caffeinated/modules/wiki/Resources).

Ex. : `{{ trans('core::locale.key') }}` core::locale.key is not clickable

**Comment by HeppyKarlsson** [comment]
I don't get intellisense for published package translations. 

Say the package publish the language file "general.php" to "resources/lang/vendor/myvendor/general.php"

To use it I have to write "myvendor::general.key" but the intellisense just tells me "general.key".

// Heppy.
