### ISSUE TITLE
Locating translations doesn't seem to work when using a locale which is not an official locale

### ISSUE THREAD

**Issue by svlcomyoo** [Haehnchen/idea-php-laravel-plugin#58]
In a project we use a database to populate translations translated by the client based on a default locale called default.

I am unable to get it to work with this locale, but when i change the locale to en and copy the lang folder and rename it to en it does work.

**Comment by svlcomyoo** [comment]
This seems to be caused by line 55 in src/de/espend/idea/laravel/stub/TranslationKeyStubIndex.java
The regex seems to limit only to 2 characters or language_country format

**Comment by Haehnchen** [comment]
@svlcomyoo so what is your path structure?

**Comment by svlcomyoo** [comment]
Our path structure is the default for laravel, translations are located in resources/lang.
The locales we use are for example: en-gb, nl-nl, nl-be etc.

**Comment by Haehnchen** [comment]
done
