### ISSUE TITLE
Plugin doesn't work for PhpStorm 2016 OS X

### ISSUE THREAD

**Issue by jaroslawziolkowski** [Haehnchen/idea-php-laravel-plugin#59]
I use phpstorm 2016, OS X 10.11.4 I have enabled plugin for project ad _ide_helper.php generated.

1. I can't save view path because after re-open settings this field still is empty.
2. Doesn't work routes, helpers (correct settings in ide-helper config)

Works only standard classes like in others projects, no Laravel.

**Comment by davidjimenez-fr** [comment]
Bump.

Same problem here on Phpstorm 2016 under Windows 10.

**Comment by realshadow** [comment]
+1

**Comment by nclifton** [comment]
+1

**Comment by normkatz** [comment]
+1 on OSX El Capitan
Plugin is installed and active in Preferences > Plugins.  If I try to add IDE Helper I consistently get an error:
php /usr/local/bin/composer require barryvdh/laravel-ide-helper:2.1-dev -n --no-progress
/usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off /usr/local/Cellar/composer/1.1.1_2/libexec/composer.phar "$@"

**Comment by Haehnchen** [comment]
just forgot to drop "view path" settings please use first submenu
