### ISSUE TITLE
Support translate in subdirectories

### ISSUE THREAD

**Issue by eduardokum** [Haehnchen/idea-php-laravel-plugin#61]
Translate works well when are not on separetade folders, when I organizing on folder like resources/lang/en/admin/menu.php and resources/lang/en/menu.php. It just suggest the one who are out the folder.

**Comment by LearnAndSolve** [comment]
Yeah, same on my side. Autocompletion displays only the entries from root of the locale folder (resources/en/auth.php, etc.) but not from the subfolders.

Here you can see autocompletion list: http://shot.devls.pro/06279045.png
Here is contents of auth/login.php file: http://shot.devls.pro/06279148.png
So I would expect to see auth/login.header, auth/login.email and other values in the autocompletion list.
