### ISSUE TITLE
Move settings form into Php related Menu

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-laravel-plugin#63]

**Comment by rlewkowicz** [comment]
So this was a bit of a pain to find. Only documentation I can find says "Restart the IDE and enable the plugin under Settings (Preferences) | Other Settings | Laravel Plugin | Enable Plugin for this Project."

I think even plugin page says: Install plugin and active it per Project under "Settings > Lavarel Plugin"

You can't really google this either and I did a shift shift search in php storm and it still didn't come up. I vote we move it back or update all the things.
