### ISSUE TITLE
model functions like where,find not poped

### ISSUE THREAD

**Issue by macnux** [Haehnchen/idea-php-laravel-plugin#65]
im using latest phpstorm 2016.2 and 2.2.1 laravel ide helper and latest version of laravel plugin

when i type Model::find 
the find function is not on the list or where ,,etc

although others like all() create are found

**Comment by jonnywilliamson** [comment]
Apart from this being in the wrong git hub repository, I'm experiencing this issue too.

Did you manage to sort it out?

**Comment by macnux** [comment]
yes 
just extend tour models from \Eloquent instead of Model
and it will work

**Comment by jonnywilliamson** [comment]
I was under the impression that this had already been taken care of in Barrys ide-helper

https://github.com/barryvdh/laravel-ide-helper/pull/305
