### ISSUE TITLE
Schema method not found!

### ISSUE THREAD

**Issue by Robot5** [Haehnchen/idea-php-laravel-plugin#70]
Laravel 5.3.x
PhpStorm 2016.2.1
laravel-ide-helper dev-master or 2.2.x

following error:

![001](https://cloud.githubusercontent.com/assets/218739/18229783/16f424a4-72b8-11e6-94b9-16c34449eecb.png)

![002](https://cloud.githubusercontent.com/assets/218739/18229787/2428de26-72b8-11e6-959d-0330a1cb1b6b.png)

**Comment by jonnywilliamson** [comment]
Would love this to work, but not sure if it's a laravel plugin issue or something that should be done with https://github.com/barryvdh/laravel-ide-helper ?

**Comment by Robot5** [comment]
@jonnywilliamson 
Already installed laravel-ide-helper!

**Comment by jonnywilliamson** [comment]
Yes, but as I said, should this be job of this plugin or the ide-helper package!?

**Comment by evgeniy-n** [comment]
Just remove \Illuminate\Support\Facades\Schema from file header (this file looks like it was generated by php artisan make:migration in 5.3. In previous versions generated migration use facade from global namespace).
laravel-ide-helper generate support for facades in global namespace e.g. \Schema, \Auth etc

**Comment by jonnywilliamson** [comment]
@evgeniy-n 

I got this issue and this one (https://github.com/barryvdh/laravel-ide-helper/pull/279) a little bit mixed up in my head.

Remembering to remove that at the top of the file is something I'll forget to do in a week. What's the best way to make this work with or without that line at the top of the file?

**Comment by ph55** [comment]
+1

Laravel 5.3 `artisan make:migration` generates migration with following namespace:

`use Illuminate\Support\Facades\Schema;`

Helper should adopt for this because the purpose of helper is automation and not fixing namespaces by hands.

**Comment by cedricziel** [comment]
This should be closed, since it's essentially about a 3rd party plugin
