### ISSUE TITLE
Plugin "Laravel Plugin" was not loaded:

### ISSUE THREAD

**Issue by AhrimanSefid** [Haehnchen/idea-php-laravel-plugin#71]
IntelliJ IDEA 2016.2.2(64)

09/04/2016
16:45   Plugin Error
            Problems found loading plugins:
            Plugin "Laravel Plugin" was not loaded: required plugin "com.jetbrains.php.blade" not installed.
            Disable Laravel Plugin
            Open plugin manager

**Comment by Haehnchen** [comment]
no error here. this plugin needs PHP Plugin. Just install it via Plugin repository
