### ISSUE TITLE
Support @push @endpush directives

### ISSUE THREAD

**Issue by vincekovacs** [Haehnchen/idea-php-laravel-plugin#73]
When using @section directive then IDE shows that where it was first created and where it was owerwritted:
![screenshot_16](https://cloud.githubusercontent.com/assets/1031595/18504151/214deb28-7a61-11e6-9d6c-3b8dc194e0d0.png)

For @push directive this does not work:
![screenshot_17](https://cloud.githubusercontent.com/assets/1031595/18504175/460cccae-7a61-11e6-8da3-b4196b92bf37.png)

**Comment by adelf** [comment]
Blade plugin has it's own issue tracker.
https://plugins.jetbrains.com/plugin/7569?pr=phpStorm

**Comment by Haehnchen** [comment]
but feature provided by this plugin

**Comment by cracki** [comment]
+1 this 👍
