### ISSUE TITLE
Add index for custom Blade directives

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-laravel-plugin#88]
https://laravel.com/docs/5.3/blade#extending-blade

```php
use Illuminate\Support\Facades\Blade;
Blade::directive('datetime')
```

**Comment by ilyaskorik** [comment]
How this work?

**Comment by adelf** [comment]
@ilyaskorik if you implement something like 
        Blade::directive('datetime', function ($expression) {
            return "<?php echo ($expression)->format('m/d/Y H:i'); ?>";
        });
in your project, PhpStorm will autocomplete @datetime() in your blade templates. Nothing special... just a little help :)

**Comment by nmfzone** [comment]
This is not working in Intellij IDEA 2020.1.1

**Comment by s-patompong** [comment]
Also not working on PHPStorm 2021.1.2

Inside boot() method of AppServiceProvider
```php
Blade::if('hasPublicEmail', function (User $user) {
    return $user->hasPublicEmail();
});
```

In blade file, no highlight at all.
```php
@hasPublicEmail($contract->talent)
```
