### ISSUE TITLE
Support Laravel 5.4 blade component

### ISSUE THREAD

**Issue by yabasha** [Haehnchen/idea-php-laravel-plugin#91]
Hello,

Add support to `@component` --- `@endcomponent` Laravel 5.4 blade feature, and other new features.

Thanx,

**Comment by Haehnchen** [comment]
https://laravel-news.com/blade-components-slots

**Comment by Haehnchen** [comment]
see also for document structure support: https://youtrack.jetbrains.com/issue/WI-34628
