### ISSUE TITLE
Remove helper-labels

### ISSUE THREAD

**Issue by JesusLeon** [Haehnchen/idea-php-laravel-plugin#94]
Hi,

something that is a bit intrusive is the placement of those unnecessary helper-labels in the middle of the code itself (see images).

![labels1](https://cloud.githubusercontent.com/assets/1864869/21740682/4b3ab1ae-d4c1-11e6-9a0c-5f50060b43d8.png)

![labels2](https://cloud.githubusercontent.com/assets/1864869/21740683/4f00d368-d4c1-11e6-99b4-a31d9015cc90.png)

It would be a lot better and cleaner if they can be toggle in a plugin-config value or removed completely.

Thanks.

**Comment by Kurre** [comment]
that's a "Parameter hints" feature by PHPStorm, not by this plugin.

To disable it: Settings - Editor - General - Appearance

You can also change its color of you want to.

**Comment by Haehnchen** [comment]
... new feature of PhpStorm 2017.1

**Comment by JesusLeon** [comment]
Cool, thanks for the clarification.
